### ISSUE TITLE
US04 - Sugerir proposta de alteração

### ISSUE THREAD

**Issue by izacristina** [fga-gpp-mds/2016.2-WikiLegis#24]
**Eu, como** cidadão registrado
**Desejo** escrever uma proposta de alteração em um segmento
**Para** exercer minha cidadania

Responsáveis: @josutk, @izacristina

**Critérios de Aceitação**

**Cenário 1:**
**Dado** que o usuário esteja logado no sistema
**E** selecione um segmento de um projeto de lei
**E** selecione a opção de sugerir alteração
**E** informe a alteração desejada
**Quando** o usuário confirmar a alteração
**Então** a alteração deverá ser confirmada através de uma mensagem
**E** mostrada na visualização do projeto de lei

**Cenário 2:**
**Dado** que o usuário esteja logado no sistema
**E** selecione um segmento de um projeto de lei
**E** selecione a opção de sugerir alteração
**E** informe a alteração desejada
**E** selecione a opção de voltar
**Então** deve-se confirmar se o mesmo deseja descartar a alteração

**Tasks**

- [x] Adicionar floating button para adição de sugestões
- [x] Criar fragment para criação da sugestão
- [x] Criar pop up para confirmação caso o usuário saia da tela de sugestão sem salvar a sugestão digitada
- [x] Criar testes de controller
- [x] Criar testes de model
- [x] Criar testes de view
