### ISSUE TITLE
US09 - Comentar Segmento

### ISSUE THREAD

**Issue by freemanpivo** [fga-gpp-mds/2016.2-WikiLegis#31]
**Eu, como** cidadão registrado
**Desejo** comentar projetos de lei e seus segmentos
**Para** expressar sua opinião em relação a ele

Responsáveis: @freemanpivo, @izacristina, @thiagonf 

**Cenário 1:**
**Dado** que o usuário esteja logado no sistema
**E** selecione um segmento de um projeto de lei
**E** selecione a opção de comentário
**E** informe o comentário desejada
**Quando** o usuário confirmar o comentário
**Então** o comentário deverá ser salvo e uma mensagem deverá informar isto

**Cenário 2:**
**Dado** que o usuário esteja logado no sistema
**E** selecione um segmento de um projeto de lei
**E** selecione a opção de comentário
**E** informe o comentário desejada
**E** selecione a opção de voltar
**Então** deve-se confirmar se o mesmo deseja descartar o comentário digitado

**Tasks**

- [x] Adicionar opção de adicionar comentário em cada segmento
- [x] Criar fragment para criação do comentário
- [x] Criar pop up para confirmação caso o usuário saia da tela do comentário sem salvar o comentário digitado
- [x] Criar testes de controller
- [x] Criar testes de model
- [x] Criar testes de view
